### PR TITLE
Updates proposed to the user resource

### PR DESCRIPTION
**Pull request by NathanBland**
What am I missing? @keawade @crodeheaver

### CODE REVIEW

**Comment by keawade** [comment]
LGTM

**Comment by crodeheaver** [comment]
@NathanBland How do you differentiate displayName vs username?

Assuming you don't care about any other info, it also LGTM.

**Comment by NathanBland** [comment]
Display name could be something like `Joe Smith`, where as username would
be `joeSmith`.

**Comment by crodeheaver** [comment]
@NathanBland  Then why not take a last name and first name, then make that a computed property? I'm fine with the display name, I typically just do the first/last name separated to allow easier searching on those fields. So it's up to you since searching happens on the server. 😉

**Comment by NathanBland** [comment]
Well, it may not be first & last name at all. Just what you want it to be

**Comment by keawade** [comment]
Perhaps we should require a first name and last name and default display name to the users first name?

EDIT: I don't really see any reason to include first or last name. Are we okay with users being anonymous to us? I think that would be fine and maybe even preferable.

**Comment by NathanBland** [comment]
I'm counting this as approval then

**Pull request merged**
